# Ambient Watcher プロジェクト設定
# このファイルでレビューの内容や観点をカスタマイズできます

# レビュー全体の有効/無効
enabled = true

# 除外パターン（これらのファイルはレビューされません）
exclude_patterns = [
    "target/**",
    "node_modules/**",
    ".git/**",
    "dist/**",
    "build/**",
    "*.min.js",
    "*.min.css",
    "vendor/**",
]

# ============================================
# レビュー設定
# ============================================

# 構文エラー・型エラーチェック
[[reviews]]
name = "構文エラー・型エラーチェック"
description = "コードの構文エラーと型の不一致を検出"
file_patterns = ["*.rs", "*.ts", "*.tsx", "*.js", "*.jsx", "*.py", "*.go"]
priority = 200
enabled = true
prompt = """
あなたはコードレビューアシスタントです。`{file_path}`を分析して、以下を日本語で報告してください：

1. 構文エラーの可能性がある箇所（未定義変数、括弧の不一致、セミコロン忘れなど）
2. 型の不一致の可能性
3. エラーがある場合は`{file_path}:行番号`の形式でリンクを提供

エラーがない場合は『構文エラーは見つかりませんでした』と答えてください。
"""

# セキュリティリスク検出
[[reviews]]
name = "セキュリティリスク検出"
description = "セキュリティ脆弱性とハードコードされた秘密情報を検出"
file_patterns = ["*"]
priority = 150
enabled = true
prompt = """
あなたはセキュリティエキスパートです。`{file_path}`を分析して、以下のセキュリティリスクを日本語で報告してください：

1. ハードコードされたAPIキー、パスワード、トークン
2. SQLインジェクション、XSSの脆弱性
3. 安全でない入力検証
4. エラー箇所は`{file_path}:行番号`形式で

リスクがない場合は『セキュリティリスクは見つかりませんでした』と答えてください。
"""

# パフォーマンス最適化
[[reviews]]
name = "パフォーマンス最適化"
description = "パフォーマンス問題と最適化の機会を検出"
file_patterns = ["*.rs", "*.go", "*.cpp", "*.c", "*.py"]
priority = 100
enabled = true
prompt = """
あなたはパフォーマンスエキスパートです。`{file_path}`を分析して、以下のパフォーマンス問題を日本語で報告してください：

1. O(n²)以上の計算量の処理
2. 不要なループやメモリリーク
3. より効率的な実装方法の提案
4. 問題箇所は`{file_path}:行番号`形式で

問題がない場合は『パフォーマンス問題は見つかりませんでした』と答えてください。
"""

# ============================================
# カスタムレビューの例（無効化されています）
# ============================================

# [[reviews]]
# name = "プロジェクト規約チェック"
# description = "プロジェクト固有のコーディング規約を確認"
# file_patterns = ["src/**/*.rs"]
# priority = 300
# enabled = false
# prompt = """
# このプロジェクトのコーディング規約に従ってレビューしてください：
# 1. 関数は30行以内
# 2. ネストは3段階まで
# 3. エラー処理は必ずResult型を使用
# """

# ============================================
# カスタムプロンプト（別ファイルから読み込む場合）
# ============================================

# [[custom_prompts]]
# id = "architecture_review"
# content = """
# アーキテクチャレビューのプロンプト...
# """
