[package]
edition = "2024"
name = "codex-cli"
version = { workspace = true }
default-run = "codex"

[[bin]]
name = "codex"
path = "src/main.rs"

[[bin]]
name = "ambient-watcher"
path = "src/main.rs"

[lib]
name = "codex_cli"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
axum = { version = "0.7", features = ["ws", "macros"] }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
chrono = { version = "0.4", features = ["serde"] }
codex-arg0 = { path = "../arg0" }
codex-chatgpt = { path = "../chatgpt" }
futures = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }
codex-common = { path = "../common", features = ["cli"] }
codex-core = { path = "../core" }
codex-protocol = { path = "../protocol" }
codex-exec = { path = "../exec" }
codex-login = { path = "../login" }
codex-mcp-server = { path = "../mcp-server" }
codex-tui = { path = "../tui" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.9"
glob = "0.3"
tower-http = { version = "0.5", features = ["fs", "trace"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
codex-protocol-ts = { path = "../protocol-ts" }

[dev-dependencies]
wiremock = "0.6"
tempfile = "3.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
